spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false

jwt:
  secret: ${JWT_SECRET_KEY}

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

logging:
  level:
    root: INFO
    kr.yuns.springinitialize: INFO
