spring:
  application:
    name: spring-initialize
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MariaDBDialect

jwt:
  access-token:
    expire-time: ${JWT_ACCESS_TOKEN_EXPIRE_TIME:3600000}
  refresh-token:
    expire-time: ${JWT_REFRESH_TOKEN_EXPIRE_TIME:604800000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
