spring:
  data:
    redis:
      host: { REDIS_HOST }
      port: { REDIS_PORT }
      password: { REDIS_PASSWORD }
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://{ DB_HOST }:{ DB_PORT }/spring-initialize
    username: { DB_USERNAME }
    password: { DB_PASSWORD }
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
jwt:
  secret: { JWT_SECRET_KEY }
  access-token:
    expire-time: 86400000
  refresh-token:
    expire-time: 604800000